[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "https://crypto-tracker-api-djbp.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 