-- Run this in Snowflake to verify the view
SELECT * FROM PORTFOLIO_PERFORMANCE; 

-- Add these queries to verify the data flow
SELECT 
    p.COIN_ID,
    h.SYMBOL,
    p.PRICE_USD,
    p.PRICE_CHANGE_24H_PCT,
    p.TIMESTAMP
FROM PRICES p
JOIN HOLDINGS h ON h.COIN_ID = p.COIN_ID
WHERE p.TIMESTAMP >= DATEADD(hour, -24, CURRENT_TIMESTAMP())
ORDER BY p.TIMESTAMP DESC;

-- Check the weighted average calculation
SELECT 
    h.CATEGORY,
    SUM(h.AMOUNT * p.PRICE_USD) as TOTAL_VALUE,
    SUM(h.AMOUNT * p.PRICE_USD * p.PRICE_CHANGE_24H_PCT) / 
    NULLIF(SUM(h.AMOUNT * p.PRICE_USD), 0) as WEIGHTED_24H_CHANGE
FROM HOLDINGS h
JOIN (
    SELECT 
        COIN_ID,
        PRICE_USD,
        PRICE_CHANGE_24H_PCT,
        ROW_NUMBER() OVER (PARTITION BY COIN_ID ORDER BY TIMESTAMP DESC) as rn
    FROM PRICES
    WHERE TIMESTAMP >= DATEADD(hour, -24, CURRENT_TIMESTAMP())
) p ON h.COIN_ID = p.COIN_ID AND p.rn = 1
GROUP BY h.CATEGORY
ORDER BY TOTAL_VALUE DESC;